version: "3.8"

services:
  backend:
    build:
      context: ./server
    container_name: gym-backend
    ports:
      - "3001:3001"
    networks:
      - gym-net

  frontend:
    build:
      context: ./client
    container_name: gym-frontend
    ports:
      - "3000:3000"
    networks:
      - gym-net

networks:
  gym-net:
