version: "3.8"

services:
  backend:
    build:
      context: ./server
    container_name: gym-backend
    ports:
      - "3001:3001"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}
    networks:
      - gym-net

  frontend:
    build:
      context: ./client
    container_name: gym-frontend
    ports:
      - "3000:3000"
    environment:
      VITE_SERVER_BASE_URL: ${VITE_SERVER_BASE_URL}
      VITE_RAZORPAY_KEY_ID: ${VITE_RAZORPAY_KEY_ID}
    depends_on:
      - backend
    networks:
      - gym-net

networks:
  gym-net:
